-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 14:09:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Activities
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Activities
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Activities` DEFAULT CHARACTER SET utf8 ;
USE `Activities` ;

-- -----------------------------------------------------
-- Table `Activities`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activities`.`Users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NULL,
  `LastName` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activities`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activities`.`Events` (
  `EventId` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NULL,
  `EventDate` DATETIME NULL,
  `EventTime` DATETIME NULL,
  `Duration` INT NULL,
  `DurationType` VARCHAR(45) NULL,
  `Description` TEXT NULL,
  `CreatedById` INT NULL,
  `CreatedByFirstName` VARCHAR(45) NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  PRIMARY KEY (`EventId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Activities`.`Participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Activities`.`Participants` (
  `ParticipantId` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `ActivityId` INT NOT NULL,
  PRIMARY KEY (`ParticipantId`, `UserId`, `ActivityId`),
  INDEX `fk_Participants_Users_idx` (`UserId` ASC),
  INDEX `fk_Participants_Activities1_idx` (`ActivityId` ASC),
  CONSTRAINT `fk_Participants_Users`
    FOREIGN KEY (`UserId`)
    REFERENCES `Activities`.`Users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participants_Activities1`
    FOREIGN KEY (`ActivityId`)
    REFERENCES `Activities`.`Events` (`EventId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
